/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IMdiAccount: typeof import('~icons/mdi/account.jsx')['default']
  const IMdiFolder: typeof import('~icons/mdi/folder.jsx')['default']
  const IMdiFolderOutline: typeof import('~icons/mdi/folder-outline.jsx')['default']
  const IMdiLinkVariant: typeof import('~icons/mdi/link-variant.jsx')['default']
  const IMdiMagnify: typeof import('~icons/mdi/magnify.jsx')['default']
}
